### PR TITLE
Added support to Django 3+ (tested with Django 4.0) & Python3+ (teste…

### PR DESCRIPTION
**Pull request by EDario333**
Added support to Django 3+ (tested with Django 4.0) & Python3+ (tested with Python 3.10.0).

### CODE REVIEW

**Comment by karanaggarwal1** [comment]
Thanks a lot for making this PR @Barukimang sorry for bothering you but can you please merge this if it looks okay and release a new version on PyPI? It would be great to have a working version of Django Jet with Django 4

**Review by Barukimang — APPROVED** [review]

**Comment by Barukimang** [comment]
Happy new year guys. Thanks for this, merged it

**Comment by karanaggarwal1** [comment]
@Barukimang thanks a lot for merging this, do you have an estimate for when a release can be made on PyPI? Really appreciate the quick action on your end.

**Comment by Barukimang** [comment]
@karanaggarwal1 should have a new release on PyPi by today or tomorrow latest, will give you a heads up once it's life

**Comment by Barukimang** [comment]
Hi @karanaggarwal1 uploaded it to Pypi! You can find it here: https://pypi.org/project/django-4-jet/

**Pull request merged**
